#能够编排管理3个容器 php redis nginx
version: "3.6"
services: #服务
    mysql-1:
        image: firren/mysql:5.7.27
        container_name: mysql-1
        networks:
            redis-network: #网络名称
                ipv4_address: 192.168.5.11  #设置IP地址
        stdin_open: true # 标准输入输出
        tty: true #标准输入输出 （和stdin_open成对出现）
        ports:
            - "3308:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - SERVER_ID=11
        volumes:
            - /Users/lichenjun/www/liuxin/mysql1909/mysql5.7.27/sh:/usr/local/src
#        user: mysql
#        entrypoint:
#            - /bin/bash
#            - /usr/local/src/mysql.sh
    mysql-2:
        image: firren/mysql:5.7.27
        container_name: mysql-2
        networks:
            redis-network: #网络名称
                ipv4_address: 192.168.5.12  #设置IP地址
        stdin_open: true # 标准输入输出
        tty: true #标准输入输出 （和stdin_open成对出现）
        ports:
            - "3309:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - SERVER_ID=12
        volumes:
            - /Users/lichenjun/www/liuxin/mysql1909/mysql5.7.27/sh:/usr/local/src
#        user: mysql

#        entrypoint:
#            - /bin/bash
#            - /usr/local/src/mysql.sh
networks:
    redis-network:
        driver: bridge
        ipam:
            config:
                - subnet: "192.168.5.0/24"
#    redis-network:
#        external:
#            name: redis-sentinel_redis-network